security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 13 # Default for bcrypt
            time_cost: 3 # Default for argon2i
            memory_cost: 65536 # Default for argon2i

    providers:
        agents:
            id: App\Security\AgentUserProvider
        agencies:
            id: App\Security\AgencyProvider
        admin_users:
            id: App\Security\AdminUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        agent:
            provider: agents
            pattern: ^/agent
            form_login:
                login_path: agent_login
                check_path: agent_login_check
                enable_csrf: true
                username_parameter: login_identifier
                default_target_path: admin_dashboard
            logout:
                path: agent_logout
                target: agent_login
            # Enable remember me functionality (optional)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /agent

        agency:
            provider: agencies
            pattern: ^/agency
            form_login:
                login_path: agency_login
                check_path: agency_login_check
                enable_csrf: true
                username_parameter: login_identifier
                default_target_path: admin_dashboard
            logout:
                path: agency_logout
                target: agency_login
            # Enable remember me functionality (optional)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: ^/agency
            
        admin:
            pattern: ^/admin
            provider: admin_users
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                enable_csrf: true
                username_parameter: login_identifier
                default_target_path: admin_dashboard
            logout:
                path: admin_logout
                target: admin_login
            # Enable remember me functionality (optional)
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /admin


    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/register$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/reset-password$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/dashboard$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/dashboard$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/dashboard$, roles: PUBLIC_ACCESS }
        - { path: ^/admin/dashboard$, roles: PUBLIC_ACCESS }   
        - { path: ^/admin/super$, roles: ROLE_SUPER_ADMIN }
        - { path: ^/admin, roles: ROLE_ADMIN }

    # Role hierarchy for better access control
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

when@test:
    security:
        password_hashers:
            App\Entity\AdminUsers:
                algorithm: auto
                cost: 4 # Lowered for tests
                time_cost: 3
                memory_cost: 10
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10